/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "cddoboboxeangripcqrn"
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || ""
export const serviceRoleKey = import.meta.env.VITE_SUPABASE_SERVICE_ROLE_KEY || ""	