/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Type definitions for Vite environment variables
interface ImportMetaEnv {
  readonly VITE_SUPABASE_ANON_KEY: string
  readonly VITE_SUPABASE_SERVICE_ROLE_KEY: string
}

interface ImportMeta {
  readonly env: ImportMetaEnv
}

export const projectId = "cddoboboxeangripcqrn"
export const publicAnonKey = (import.meta as any).env?.VITE_SUPABASE_ANON_KEY || ""
export const serviceRoleKey = (import.meta as any).env?.VITE_SUPABASE_SERVICE_ROLE_KEY || ""	